### PR TITLE
Adding fusion TOC back

### PR DESCRIPTION
**Pull request by AlexJerabek**

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[a2db600](https://github.com/OfficeDev/office-scripts-docs/commits/a2db6006daf228fd4bacf55bf21470d1b7899618)_: 

:clock10: **Pending**: waiting for processors ([70](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 70 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[a2db600](https://github.com/OfficeDev/office-scripts-docs/commits/a2db6006daf228fd4bacf55bf21470d1b7899618)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-Fusion/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C12%5C13%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C201912130124563326-50%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GOmO84nNuMTBxf1DSNJ5dbNo7AWaTxaYJpK%2F%2B4Xknnc%3D&st=2019-12-13T01%3A21%3A01Z&se=2020-01-13T01%3A26%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[8c5e7c2](https://github.com/OfficeDev/office-scripts-docs/commits/8c5e7c26919b24dff401fb7e5003bb0220767e81)_: 

:clock10: **Pending**: waiting for processors ([22](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 22 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by AlexJerabek** [comment]
The build stalled, but a manual rebuild appears to have worked:
image

**Pull request merged**
