### PR TITLE
Create SendingEmailsUsingOfficeScriptAndPowerAutomate

### PR DESCRIPTION
**Pull request by mhusk**

### CODE REVIEW

**Comment by AlexJerabek** [comment]
Hi @mhusk,

Thanks for creating this PR. It looks like it'll help people automate their reminder processes. 

I have a couple questions about this sample and how you'd like to proceed.

1) How would you like to differentiate this sample from the [existing email reminder tutorial](https://docs.microsoft.com/en-us/office/dev/scripts/tutorials/excel-power-automate-returns)? I haven't fully gone through your sample yet, but I want to make sure that the samples solve different problems and that both samples are useful. If the existing tutorial is missing a fundamental element (or not discoverable), I'd appreciate your help fixing that.
2) To better integrate this sample with our docs, it'll need to follow the Microsoft style guidelines. I'm completely happy to make those changes, but I wanted you to be aware of that. This would be some things for accessibility (header structure, alt-text, etc) and some things for compliance (images stored in this repo). Are you okay with those sorts of changes?

Also, before we can accept this submission in any form, please sign the Contribute License Agreement that the bot linked to a few days ago. Thanks!

**Comment by mhusk** [comment]
Hey @AlexJerabek,

This is a good point. I am not sure if this adds anything terribly new to the tutorial you just linked. 

I think the only difference is my script passes a little more information.

I talked with Nancy and she asked me to make a little write-up of how I used Office Script and Power Automate, so if this isn't a good example to add to what you have already put together all good to me!

**Comment by mhusk** [comment]
Also, I might need to talk with my boss before I sign that agreement.

**Comment by AlexJerabek** [comment]
@mhusk Yeah, please confirm the CLA doesn't violate anything on your end of things. If there's some issue with it, please consider adding this sample to a blog or something or other Scripts users can find it.

**Comment by AlexJerabek** [comment]
Hi @mhusk,
Any update on the CLA?

**Pull request closed without merging**
