### PR TITLE
Update the CG notice file

### PR DESCRIPTION
**Pull request by evanargelion**

### CODE REVIEW

**Comment by evanargelion** [comment]
I guess the build is triggered by a new commit? Could I trigger a rebuild somehow? Just fixed the OpenPublishing.Build issue.

**Comment by AlexJerabek** [comment]
@evanargelion I'll see if I can trigger one in OPS. You can always make a minor change (like add a space) to trigger a build.

**Comment by evanargelion** [comment]
@AlexJerabek Done.

**Comment by AlexJerabek** [comment]
@evanargelion. The changes seem fine (no f-bombs!), but why is the licensing file doubling in size (35K lines to 74K lines)? Were there duplicates that previously got stripped out? Or do scripts use that many more libraries these days?

**Comment by evanargelion** [comment]
@AlexJerabek Looked into the f-bomb package "path-is-inside", it is introduced by Cypress and Serve package we using in devdepencency.

Tried to exclude these for the MakerCodeEditor-Publish pipeline, however they are not showing in the list of package that CG UI shows us, saying they have already excluded cypress and serve, but notice file still having that f-bomb.

I have opened a bug on CG side, while generated this notice file from another pipeline that we can exclude the problematic package, but includes a bunch of other devdependency in the file...

**Review by AlexJerabek — APPROVED** [review]

**Comment by evanargelion** [comment]
Thanks!

**Pull request merged**
