### PR TITLE
Update config to enable docfx v3

### PR DESCRIPTION
**Pull request by v-caxian**
[AB#249326](https://dev.azure.com/ceapex/Engineering/_workitems/edit/249326)

This Pull Request is for docfxv3 migration, after the Pull Request merged, the repository will be built with docfxv3 instead of docfxv2.

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[2753660](https://github.com/OfficeDev/office-scripts-docs/commits/27536605820231711e00829afea44e280a672890)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-114a725b)
[docs/404.md](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/docs/404.md) | :warning:Warning | | [Details](#user-content-9684adf0-114a725b)
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

<a id="114a725b"></a>
###
 - **[Warning-UserDefinedServiceAccountOAuthScopeInsufficient]** `````User defined service account 'o365devx' cannot be used to build repository https://github.com/OfficeDev/office-scripts-docs due to lack of correct OAuth Scopes. The Build will fallback to use the repository owner's account to continue the build. To resolve this warning, please log onto the Docs Portal (https://ops.microsoft.com) with the account 'o365devx' or ask the repository admin(s) to go to Docs Portal and update user defined service account list.`````

<a id="9684adf0-114a725b"></a>
### [docs/404.md](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/docs/404.md)
 - **Line 0, Column 0**: **[Warning-custom-404-page]** `````Custom 404 page will be deprecated in future. Please remove the 404.md file to resolve this warning.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C9%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202007090846338635-144%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SlT6jMhzElIfeXB%2FTanklPtGPjhCuITXfxOwQ9gyinw%3D&st=2020-07-09T08%3A41%3A58Z&se=2020-08-09T08%3A46%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AlexJerabek** [comment]
Hi @v-caxian, 
The changes seem fine, but could you please include the removal of the 404 page in the PR? That way, we can check in to master without any build warnings. Relatedly, can you tell us what the new 404 experience will be like?
Thanks!

**Comment by live1206** [comment]
> Hi @v-caxian,
> The changes seem fine, but could you please include the removal of the 404 page in the PR? That way, we can check in to master without any build warnings. Relatedly, can you tell us what the new 404 experience will be like?
> Thanks!

Hi @AlexJerabek ,

The custom page is not supported in v3 anymore.
Could you remove it afterwards since this PR is just for v3 migration?
The only 404 page for docs site would be https://docs.microsoft.com/en-us/404.
Thanks!

**Comment by o365devx** [comment]
Docs Build status updates of commit _[ca053f5](https://github.com/OfficeDev/office-scripts-docs/commits/ca053f5f26fa4cbfb49e3a28d64f02071988752c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-4659ee51)
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docs/404.md](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/docs/404.md) | :white_check_mark:Succeeded | |

<a id="4659ee51"></a>
###
 - **[Warning-UserDefinedServiceAccountOAuthScopeInsufficient]** `````User defined service account 'o365devx' cannot be used to build repository https://github.com/OfficeDev/office-scripts-docs due to lack of correct OAuth Scopes. The Build will fallback to use the repository owner's account to continue the build. To resolve this warning, please log onto the Docs Portal (https://ops.microsoft.com) with the account 'o365devx' or ask the repository admin(s) to go to Docs Portal and update user defined service account list.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C14%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202007142244154596-144%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C7lWUq9zd2xxkTvlL8LbzEYO5wIh%2Btvc3MSrA9JcVP4%3D&st=2020-07-14T22%3A39%3A41Z&se=2020-08-14T22%3A44%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AlexJerabek** [comment]
@v-caxian, Do you have any guidance on the SSO-related warning that's being generated for o365devx? That only seems to be happening with these config file changes.

**Comment by fenxu** [comment]
> 
> 
> @v-caxian, Do you have any guidance on the SSO-related warning that's being generated for o365devx? That only seems to be happening with these config file changes.

@AlexJerabek the GitHub OAuth APP OAuth Scope of v3 is changed so that the warning comes. To migrate this issue, please go to [Docs Portal](https://ops.microsoft) and login with GH account **o365devx** account and re-OAuth the APP. Then the warning will be gone.

**Comment by o365devx** [comment]
Docs Build status updates of commit _[ca053f5](https://github.com/OfficeDev/office-scripts-docs/commits/ca053f5f26fa4cbfb49e3a28d64f02071988752c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-5016a115)
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docs/404.md](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/docs/404.md) | :white_check_mark:Succeeded | |

<a id="5016a115"></a>
###
 - **[Warning-UserDefinedServiceAccountOAuthScopeInsufficient]** `````User defined service account 'o365devx' cannot be used to build repository https://github.com/OfficeDev/office-scripts-docs due to lack of correct OAuth Scopes. The Build will fallback to use the repository owner's account to continue the build. To resolve this warning, please log onto the Docs Portal (https://ops.microsoft.com) with the account 'o365devx' or ask the repository admin(s) to go to Docs Portal and update user defined service account list.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C15%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202007150740402189-144%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rg%2BWF5crGgRO2BSvRuQ7RIHBXNScInDbV6cOQJPKFV8%3D&st=2020-07-15T07%3A36%3A08Z&se=2020-08-15T07%3A41%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AlexJerabek** [comment]
Docs Build status updates of commit _[ca053f5](https://github.com/OfficeDev/office-scripts-docs/commits/ca053f5f26fa4cbfb49e3a28d64f02071988752c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docs/404.md](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/docs/404.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C15%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202007150827381492-144%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lYRxgjC05ujOxZMIpqktbthHANZPIvtZU1ilQ4yDrA4%3D&st=2020-07-15T08%3A32%3A39Z&se=2020-08-15T08%3A37%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AlexJerabek** [comment]
Docs Build status updates of commit _[ca053f5](https://github.com/OfficeDev/office-scripts-docs/commits/ca053f5f26fa4cbfb49e3a28d64f02071988752c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docs/404.md](https://github.com/OfficeDev/office-scripts-docs/blob/docs-build-v3/docs/404.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C7%5C15%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202007150850395456-144%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y0qtP1miaXJXQHWZ7fpZA2HF2kHeP0mx%2FDq0nAK76%2Bw%3D&st=2020-07-15T08%3A55%3A25Z&se=2020-08-15T09%3A00%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
