### PR TITLE
Note about connector scope increase

### PR DESCRIPTION
**Pull request by AlexJerabek**
Review site: https://review.docs.microsoft.com/en-us/office/dev/scripts/develop/power-automate-integration?branch=AlexJ-DLP

### CODE REVIEW

**Comment by o365devx** [comment]
Docs Build status updates of commit _[1a4dbc1](https://github.com/OfficeDev/office-scripts-docs/commits/1a4dbc1803423fa9635328071e713515275795a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C16%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006162305374245-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bdU11vOGV4nbnf8ghKM%2BuKs08Al518m7zUvPiPYXgEQ%3D&st=2020-06-16T23%3A01%3A51Z&se=2020-07-17T23%3A06%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by danielgwilson** [comment]
I think this is the relevant section?

> The "Run script" action gives people who use the Excel connector significant access to your workbook and its data. Only people in your organization who are trusted with Power Automate flows can use this connector. However, your administrator should be aware about this increase in workbook exposure. They cannot control individual actions on the Excel controller and would have to restrict access through the Office Scripts administrator controls.

I'm a bit concerned that this doesn't adequately describe the actual problem—however, if everyone else is happy I'm willing to defer to oSec and Power Automate's DLP team to confirm whether this is clear enough.

**Comment by AlexJerabek** [comment]
@danielgwilson, Can you highlight what you're concerned we're missing?

**Comment by o365devx** [comment]
Docs Build status updates of commit _[75234f7](https://github.com/OfficeDev/office-scripts-docs/commits/75234f7f65e1510ddeb35618ffa7c420e9641a4a)_: 

:clock10: **Pending**: waiting for processors ([71](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 71 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[75234f7](https://github.com/OfficeDev/office-scripts-docs/commits/75234f7f65e1510ddeb35618ffa7c420e9641a4a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C22%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006222218088070-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3CPJQHC33f4BqXvlc0vfsZFhiv11b%2F7MmHypGqvtkm4%3D&st=2020-06-22T22%3A14%3A27Z&se=2020-07-23T22%3A19%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[ba22c72](https://github.com/OfficeDev/office-scripts-docs/commits/ba22c72f28807c8e7135ebb98215afc8043d670b)_: 

:clock10: **Pending**: waiting for processors ([26](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 26 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[458acc6](https://github.com/OfficeDev/office-scripts-docs/commits/458acc6df4c182ff9ccd4c712fce46aa77ed22b4)_: 

:clock10: **Pending**: waiting for processors ([26](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 26 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[ba22c72](https://github.com/OfficeDev/office-scripts-docs/commits/ba22c72f28807c8e7135ebb98215afc8043d670b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/external-calls.md) | :white_check_mark:Succeeded | |
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C24%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006241920435200-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jkkrqZJcG4msGswGpSalQCnvat05Q2u0f%2BeAMzMMBAc%3D&st=2020-06-24T19%3A17%3A17Z&se=2020-07-25T19%3A22%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[9995053](https://github.com/OfficeDev/office-scripts-docs/commits/999505344b27ea297ce0836d8b49ab7a631b039b)_: 

:clock10: **Pending**: waiting for processors ([27](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 27 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[458acc6](https://github.com/OfficeDev/office-scripts-docs/commits/458acc6df4c182ff9ccd4c712fce46aa77ed22b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/external-calls.md) | :white_check_mark:Succeeded | |
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C24%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006241921590143-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=inlEwEzwT3HO54D7qwuVuZgXpCejqk6WMCFGfdn2cMU%3D&st=2020-06-24T19%3A18%3A48Z&se=2020-07-25T19%3A23%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[dcd4e90](https://github.com/OfficeDev/office-scripts-docs/commits/dcd4e90c119ae7eb2059c296723dd7d68084b379)_: 

:clock10: **Pending**: waiting for processors ([27](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 27 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

**Comment by o365devx** [comment]
Docs Build status updates of commit _[9995053](https://github.com/OfficeDev/office-scripts-docs/commits/999505344b27ea297ce0836d8b49ab7a631b039b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/external-calls.md) | :white_check_mark:Succeeded | |
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C24%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006241923116450-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pQQg%2B5Hgoc3p%2F78%2F7eDDNYCBFE4hjRzqomvTIoZd3Lg%3D&st=2020-06-24T19%3A20%3A07Z&se=2020-07-25T19%3A25%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[dcd4e90](https://github.com/OfficeDev/office-scripts-docs/commits/dcd4e90c119ae7eb2059c296723dd7d68084b379)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/external-calls.md) | :white_check_mark:Succeeded | |
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C24%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006241924098090-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hHejaEN5kBohfXqDF5Jox4KPXZqeujN3olYAlidY6nU%3D&st=2020-06-24T19%3A21%3A46Z&se=2020-07-25T19%3A26%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[9025af9](https://github.com/OfficeDev/office-scripts-docs/commits/9025af97c44f0d10ceec020a428c27b0a2b56d85)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4c1cd4e0)
[_dependentPackages/CommonPlugins/tools/JoinTOC.ps1](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/_dependentPackages/CommonPlugins/tools/JoinTOC.ps1) | :x:Error | | [Details](#user-content-402d9d56-4c1cd4e0)

<a id="4c1cd4e0"></a>
###
 - **[Error-OPSPlugins_InternalError]** 
`````
YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.DataContracts.Common.TocItemViewModel, Microsoft.DocAsCode.DataContracts.Common, Version=2.37.2.0, Culture=neutral, PublicKeyToken=null
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(IParser reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(IParser parser, Type type, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   at Microsoft.OpenPublishing.PluginHelper.TocHelper.TryParseTocAsObjectModel(String tocPath, TocItemViewModel& toc)
   at Microsoft.OpenPublishing.PluginHelper.TocHelper.InjectTocMetadata(String tocPath, String metaName, String metaValue)
   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)
   at JoinTOC.Program.Main(String[] args)
`````

<a id="402d9d56-4c1cd4e0"></a>
### [_dependentPackages/CommonPlugins/tools/JoinTOC.ps1](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/_dependentPackages/CommonPlugins/tools/JoinTOC.ps1)
 - **Line 108**: **[Error]** `````Error happened when executing plug-in script _dependentPackages/CommonPlugins/tools/JoinTOC.ps1 at step docset_prebuild. Please check your .openpublishing.publish.config.json?on the configuration of the plug-ins or ask for help?in Docs Support teams channel. Detailed error message: {"message":"YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.DataContracts.Common.TocItemViewModel, Microsoft.DocAsCode.DataContracts.Common, Version=2.37.2.0, Culture=neutral, PublicKeyToken=null\r\n   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(IParser parser, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)\r\n   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(IParser reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)\r\n   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(IParser parser, Type type, IValueDeserializer deserializer)\r\n   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input, IValueDeserializer deserializer)\r\n   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)\r\n   at Microsoft.OpenPublishing.PluginHelper.TocHelper.TryParseTocAsObjectModel(String tocPath, TocItemViewModel& toc)\r\n   at Microsoft.OpenPublishing.PluginHelper.TocHelper.InjectTocMetadata(String tocPath, String metaName, String metaValue)\r\n   at JoinTOC.TOCMerger.Merge(CommandLineOptions opt)\r\n   at JoinTOC.Program.Main(String[] args)","source":"","file":null,"line":null,"message_severity":0,"date_time":"2020-06-24T21:46:58.149769Z","code":"OPSPlugins_InternalError","log_item_type":1}.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C24%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006242146126343-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MtD0kdCroc0O%2FKYOynvpyU%2BkZXPRUAtXsxvMm8WfkoQ%3D&st=2020-06-24T21%3A42%3A03Z&se=2020-07-25T21%3A47%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[9b8edd2](https://github.com/OfficeDev/office-scripts-docs/commits/9b8edd237595568919f608467e7c6c7b28a175a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/external-calls.md) | :white_check_mark:Succeeded | |
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C24%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006242215425676-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sejKPvA6eQIKlFhylec%2Fciu%2FITdhmZLV6VDidBa7rR0%3D&st=2020-06-24T22%3A11%3A56Z&se=2020-07-25T22%3A16%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[e5565b1](https://github.com/OfficeDev/office-scripts-docs/commits/e5565b1b4e7c9622e3b47bada6d153221e6ee4d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/external-calls.md) | :white_check_mark:Succeeded | |
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C24%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006242352539006-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C1ReWOEbdA0Q3XLK1ZzaegJrzVZcFwHKR9Kx0jPcuFA%3D&st=2020-06-24T23%3A49%3A14Z&se=2020-07-25T23%3A54%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by o365devx** [comment]
Docs Build status updates of commit _[07e918e](https://github.com/OfficeDev/office-scripts-docs/commits/07e918eea0688e9056b7ff6282bd03c9c3b9e379)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/develop/external-calls.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/external-calls.md) | :white_check_mark:Succeeded | |
[docs/develop/power-automate-integration.md](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/develop/power-automate-integration.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/OfficeDev/office-scripts-docs/blob/AlexJ-DLP/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C6%5C25%5C918d1c35-f3a4-631b-1edf-a1a2af22eee5%5CPullRequest%5C202006251711391371-122%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zbeBIHgVRihqqVRb51G%2FfxDBziHdXxwbqVUxh6POhU4%3D&st=2020-06-25T17%3A08%3A05Z&se=2020-07-26T17%3A13%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/918d1c35-f3a4-631b-1edf-a1a2af22eee5?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by AlexJerabek** [comment]
@danielgwilson and @peronald approved off-line. Checking in.

**Pull request merged**
